image:
  name: luggitapp/benthos-sheets-output-plugin
  tag: latest

secrets:
  serviceAccountSecretName: google-service-account
  serviceAccountSecretSubPath: sva.json

config:
  http:
    address: ${HTTP_ADDRESS:0.0.0.0:4195}
    
  input:
    nats:
      urls:
        - nats://nats:4222
      queue: benthos_queue
      subject: test-sheet

  pipeline:
    processors:
      - bloblang: |
          root = [
            field1, 
            field2, 
            field3,
          ]
    threads: 1

  output:
    type: sheets
    plugin:
      sheetId: "<your-sheet-id>"

  logger:
    prefix: benthos
    level: ALL
    format: json
    add_timestamp: true